# Generated by Django 5.2.7 on 2025-10-05 01:29

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('unit', models.CharField(choices=[('ml', 'milliliters'), ('g', 'grams'), ('pcs', 'pieces')], max_length=100)),
                ('is_global', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(related_name='medicines', to='medicine_management_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='PendingMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_closed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('a', 'approved'), ('r', 'rejected'), ('p', 'pending')], max_length=100)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True)),
                ('medicine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medicine_management_app.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('morning_time', models.TimeField(blank=True, null=True)),
                ('afternoon_time', models.TimeField(blank=True, null=True)),
                ('evening_time', models.TimeField(blank=True, null=True)),
                ('night_time', models.TimeField(blank=True, null=True)),
                ('is_administrator', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReserveMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_management_app.medicine')),
                ('reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine', to='medicine_management_app.reserve')),
            ],
        ),
        migrations.CreateModel(
            name='ReserveActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumed_amount', models.FloatField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('reserve_medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_management_app.reservemedicine')),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_from', models.IntegerField(blank=True, null=True)),
                ('age_to', models.IntegerField(blank=True, null=True)),
                ('age_unit', models.CharField(blank=True, choices=[('y', 'years'), ('m', 'months'), ('d', 'days')], max_length=100, null=True)),
                ('comments', models.TextField(blank=True)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('hours_between', models.IntegerField(blank=True, null=True)),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_management_app.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_from', models.DateField(default=datetime.date.today)),
                ('duration_to', models.DateField(blank=True, null=True)),
                ('morning_time', models.TimeField(blank=True, null=True)),
                ('afternoon_time', models.TimeField(blank=True, null=True)),
                ('evening_time', models.TimeField(blank=True, null=True)),
                ('night_time', models.TimeField(blank=True, null=True)),
                ('last_intake', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reserve_medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_management_app.reservemedicine')),
                ('usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_management_app.usage')),
            ],
        ),
        migrations.CreateModel(
            name='Dosage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('time', models.CharField(choices=[('Morning', '06:00-12:00'), ('Afternoon', '12:00-17:00'), ('Evening', '17:00-21:00'), ('Night', '21:00-06:00')], max_length=100)),
                ('usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_management_app.usage')),
            ],
        ),
    ]
