# Generated by Django 5.2.7 on 2025-10-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingmedicine',
            name='review_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dosage',
            name='time',
            field=models.CharField(choices=[('Morning', '06:00-12:00'), ('Afternoon', '12:00-17:00'), ('Evening', '17:00-21:00'), ('Night', '21:00-00:00')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pendingmedicine',
            name='status',
            field=models.CharField(choices=[('a', 'approved'), ('r', 'rejected'), ('p', 'pending')], default='pending', max_length=100),
        ),
    ]
