# Generated by Django 5.2.7 on 2025-11-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_management_app', '0002_pendingmedicine_review_comments_alter_dosage_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('guest', 'guest'), ('admin', 'admin'), ('client', 'client')], default='guest', max_length=10),
        ),
    ]
